name: UsagiPass Frontend CI

env:
  VITE_URL: https://up.turou.fun/api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml" # we consider version has been bumped

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        working-directory: ./web
        run: npm install

      - name: Run build task
        working-directory: ./web
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "web/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}/up.turou.fun
